name: OCaml CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  run:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.x
    - name: Install
      run: | 
        opam install -t . --deps-only
        opam install dune
        opam install ounit2.2.2.6
        opam install ocamlformat
        opam install qcheck
    - name: Lint
      run: opam exec -- dune fmt --action-stdout-on-success=swallow --action-stderr-on-success=must-be-empty
    - name: Build
      run: opam exec -- dune build
    - name: Test
      run: opam exec -- dune runtest